mailgun/documentation

- source/_templates/layout.html
Adds Ace editor to all code samples on click. Users can then edit params in browser.
> Ace of spades

- source/api-unsubscribes.rst
- source/user_manual.rst
Key changes:
* References to the individual tabs --> Suppressions tab
* References to turning on unsubscribes --> Now lives under domain settings
@bradgignac Mind giving this a quick check? Not that much had to be changed.
> Updating docs for new suppressions

- source/samples/send-inline-image.rst
> Removed at sign

- source/api-domains.rst
- source/api-sending.rst
- source/samples/get-connection.rst
- source/samples/send-connection.rst
- source/samples/update-connection.rst
- source/user_manual.rst
Added documentation for new Mailgun feature: TLS connection control.
> TLS connection control

- source/_static/insert-api-key.js
in order to properly replace api key examples in the docs
> look up features

- source/wrappers.rst
> Update wrappers.rst rest-client link

- source/_templates/layout.html
Adds new resources dropdown to nav so consistent with corpsite.
> Add resources to docs nav

- source/_templates/layout.html
> Change login and signup

- source/user_manual.rst
Old DNS articles no longer work. Replaced them with valid articles
> Update DNS articles

- source/wrappers.rst
This is already shown in libraries.rst - wrappers.rst needs to show the same.
> Updated minimum PHP version info

- source/user_manual.rst
I did aslo add a check if the digest is fresh.
> Added an example in PHP for verifying the digest.

- source/libraries.rst
Related to https://github.com/mailgun/mailgun-php/pull/94
> Updated PHP docs for version 2.0 of the mailgun client

- source/samples/update-list-member.rst
Issue 122 - Put does not accept array as second argument
> PHP add http_build_query() to put method

- source/api-events.rst
> Add `id` field to all event samples

- source/api-sending.rst
- source/user_manual.rst
Also removed duplicate `content-id-map` line and added the `domain` parameter.
> Add note about 'message-url' parameter

- source/api-export.rst
- source/samples/create-export.rst
> Updated exports csharp sample and exports doc

- source/libraries.rst
The hyperlinks are not rendering correctly.
> Fix hyperlink on luvit

- source/user_manual.rst
> updating SMTP batch sending example

- source/api-ips.rst
- source/api_reference.rst
- source/samples/add-domain-ip.rst
- source/samples/get-domain-ips.rst
- source/samples/get-ip.rst
- source/samples/get-ips.rst
- source/samples/remove-domain-ip.rst
Documentation of the API for dedicated IP management.
> Add dedicated IP management documentation

- source/samples/get-ips.rst
> Change IPs API curl example

- source/libraries.rst
Updated java requirements from jersey to unirest.
> Updated Java requirements.

- source/api-domains.rst
https://mailgun.atlassian.net/browse/PIP-249
> Subdomain self DKIM authority

- source/_static/mg.css
- source/_templates/layout.html
Update subnav (code samples) css:
1. Remove background hover
2. Change container to container-fluid
3. Add left and right padding to align with toplevel navigation
> Update subnav css.

- source/_static/mg.css
CSS updates:
1) Remove the border for the `pre` tag
2) Change .subnav position to fixed (from absolute)
3) Remove position 'top' from .subnav-fixed
> Remove pre tag border; set code preference bar to fixed.

- source/_templates/layout.html
- source/_templates/layoutBAK.html
1. Update links under "Solutions" heading.
2. Change top level "Resources" to "Docs".
3. Update links under the new "Docs" heading.
> Update navigation links.

- source/api-intro.rst
Add Postman Integration section and button.
Fix errors on build.
> Add postman button to API Introduction page.

- source/samples/add-webhook.rst
so others dont lose 20 minutes ;)
> incorrect URL on webhooks Nodejs example

- source/samples/send-mime-message.rst
Related to issue [mailgun-js #171](https://github.com/bojand/mailgun-js/issues/171).
> Update Node.js send mime example to use nodemailer module

- source/samples/send-simple-message.rst
> Updated the PHP send example

- source/api-unsubscribes.rst
Hello,
This PR is related to [my PR I made for your PHP SDK](https://github.com/mailgun/mailgun-php/pull/432).
As I mentioned, your API returns an array of tags instead of a simple string.
Is it ok for you ?
Best Regards,
Quentin.
> Update unsubscribe tags documentation.

- source/samples/change-pwd-credentials.rst
Corrected url to change credentials
> Corrected url to change credentials

- source/api-email-validation.rst
Just make sure we use the correct indentation
> Fixed typo

- source/api-bounces.rst
- source/api-complaints.rst
- source/api-intro.rst
- source/api-mailinglists.rst
- source/api-tags.rst
- source/api-unsubscribes.rst
- source/api-webhooks-deprecated.rst
- source/samples/add-unsubscribe-all.rst
- source/samples/create-route.rst
- source/samples/delete-domain.rst
- source/samples/get-webhook-deprecated.rst
- source/samples/get-webhooks.rst
- source/user_manual.rst
Fix build errors which result in code examples not highlighted properly and links not working.
> Fix code syntax

- source/libraries.rst
This adds a Kotlin library implementation. Let me know if you all are cool with this. 
Also, I corrected some caps-case usages of GitHub 😄
> Add Kotlin library

- source/samples/create-domain.rst
- source/samples/get-domain.rst
* Changed signature of CreateDomain() Now returns JSON response
* Changed signature of GetDomain() Now returns a single DomainResponse
> Updated mailgun-go examples for mailgun-go v3.3.0 release

- source/api-intro.rst
Closes #357 and #362. However we should add a section that expands upon the differences in regions and when/why a customer would choose the EU region.
> Mention the EU and non EU endpoints

- source/api-sending.rst
> Clarify acceptable values for booleans

- source/api-templates.rst
- source/user_manual.rst
Some suggested grammar and wording changes
> Minor wording changes

- source/libraries.rst
Help clear up confusion on how to install mailgun-go v3
> Added go to libraries page

- source/api-intro.rst
> Favor YOUR_API_KEY as a placeholder instead of a fake key

- source/user_manual.rst
Add missing mailing list events to list of events in response to #320
> Add mailing list events

- source/api-events.rst
Added missing event structures for mailing list events #320 #398
> Added list event structures

- source/samples/add-domain.rst
- source/samples/create-domain.rst
- source/samples/templates/create-template-usage.rst
- source/samples/templates/template-create-version.rst
- source/samples/templates/template-create.rst
- source/samples/templates/template-delete.rst
- source/samples/templates/template-get-active.rst
- source/samples/templates/template-get-all.rst
- source/samples/templates/template-get.rst
- source/samples/templates/template-update.rst
- source/samples/templates/version-create.rst
- source/samples/templates/version-delete.rst
- source/samples/templates/version-get-all.rst
- source/samples/templates/version-get.rst
- source/samples/templates/version-update.rst
Add missing golang template examples.
> Added golang template examples

- source/user_manual.rst
Mailgun requires the route filter to be on one line.
> Put route filter on one line (#412)

- source/samples/send-inline-image.rst
added inline field for completeness of sending inline image in java
> added inline parameter in sending with inline image

- source/api-email-validation.rst
Updated "reason" field to reflect an array, and updated risk possibles to lowercase, also some formatting changes
> Updates and formatting changes

- source/api-email-validation.rst
https://mailgun.atlassian.net/browse/VAL-189
> VAL-189: Add reasons table to email_validations api documentation

- source/samples/get-validate.rst
Go example is missing the single space indentation
> FD-1874: fix indentation error for go example

- source/user_manual.rst
The instructions for checking the authenticity of a webhook message previously instructed using the "API Key" as the SHA HMAC key, however when interpreting this as the "Private API key" under Settings > API Keys, this results in validation failing. Only after some time struggling and experimenting did I discover that the expected key is the "HTTP webhook signing key", not the "Private API key".
This commit updates the "Securing Webhooks" instructions to use the "Webhook Signing Key" (as it is labeled across the Mailgun web app) to make it clearer which key should be used.
> Update User Manual > Securing Webhooks

- source/api-sending.rst
https://mailgun.atlassian.net/browse/STO-82
Adding STO to sending API
> STO-82 Add STO Documentation

- source/libraries.rst
Added informations for Perl users (HTTP and API libraries, Plugin for Mojolicious and Email::Sender Transport module).
> added Perl section

- source/user_manual.rst
> Fix typo in user manual

- source/api-email-validation.rst
- source/samples/get-bulk-validations.rst
https://mailgun.atlassian.net/browse/VAL-531
> VAL-531 Adding pagination to bulk validation list endpoint.

- source/api-email-validation.rst
- source/samples/create-bulk-preview.rst
- source/samples/delete-bulk-preview.rst
- source/samples/get-bulk-preview.rst
- source/samples/get-bulk-previews.rst
- source/samples/put-bulk-preview.rst
https://mailgun.atlassian.net/browse/VAL-555
> VAL-555 Adding bulk preview.

- source/_static/top_navigation.css
Reverts mailgun/documentation#488
> Revert "fix for submenus not staying open when cursor moves down page above o…"

- source/api-email-validation.rst
- source/samples/post-validate.rst
https://mailgun.atlassian.net/browse/VAL-712
> VAL-712: add single validations POST documentation

- source/api-email-validation.rst
https://mailgun.atlassian.net/browse/VAL-604
> VAL-604 Added API documentation for provider_lookup flag

- source/api-email-validation.rst
https://mailgun.atlassian.net/browse/VAL-768
> VAL-768 Remove invalid bounce statement.

- source/api-email-validation.rst
https://mailgun.atlassian.net/browse/VAL-730
> VAL-730: EU Validations Note

- source/api-email-validation.rst
Updated Email Validations docs to include the "root_address" field.
> Update Email Validation response

- source/user_manual.rst
Trying to add more clarity around which ports require TLS and which are upgradable to TLS
> Reworded port numbers and TLS requirements

- source/api-sending.rst
- source/samples/decode-quoted-printable.rst
- source/samples/resend-simple-message.rst
- source/samples/send-complex-message.rst
- source/samples/send-connection.rst
- source/samples/send-inline-image.rst
- source/samples/send-message-by-template-id.rst
- source/samples/send-message-no-tracking.rst
- source/samples/send-message-template-v.rst
- source/samples/send-mime-message.rst
- source/samples/send-scheduled-message.rst
- source/samples/send-simple-message.rst
- source/samples/send-tagged-message.rst
- source/samples/send-template-message.rst
- source/user_manual.rst
This is the first PR for updating the node.js examples. 
https://github.com/mailgun/mailgun.js/issues/126
It includes updates only for sending messages.
> Update Node.js examples for sending messages

- source/api-ip-pools.rst
- source/samples/ip_pools/create_ip_pool.rst
- source/samples/ip_pools/delete_ip_pool.rst
- source/samples/ip_pools/get_ip_pools_list.rst
- source/samples/ip_pools/link_ip_pool.rst
- source/samples/ip_pools/unlink_ip_pool.rst
- source/samples/ip_pools/update_ip_pool.rst
This PR adds bash and node-js examples for ip_pools functionality
> Add examples for ip-pools

- source/api-email-validation-deprecated.rst
- source/api-email-validation.rst
- source/api-mailinglists.rst
- source/samples/create-list-validation.rst
- source/samples/delete-list-validation.rst
- source/samples/get-domain-tracking.rst
- source/samples/get-list-validation.rst
- source/user_manual.rst
change "validations" to "verifications"
> "validations" to "verifications" changes

- source/api-email-validation-deprecated.rst
- source/api-email-validation.rst
- source/user_manual.rst
These finalize the changes from "email validations" to "email verifications", and the exact verbiage has been reviewed and approved.
> Final verification changes

- source/user_manual.rst
https://mailgun.atlassian.net/browse/PIP-1446
> PIP-1446: Add documentation for bot opens and clicks

- source/_templates/layout.html
upgrades capability of Forethought Solve to use workflows
> upgrade forethought functionality

- source/samples/send-inline-image.rst
Fixing an example, for more info check [this PR](https://github.com/mailgun/mailgun-go/pull/297)
> Fix golang inline image example

- source/_static/rudderstack.js
- source/_templates/layout.html
https://mailgun.atlassian.net/browse/GRO-692
- Adds rudderstack js snippet for page view tracking
- Directly used the prod public key since I don't think there is any "staging" env for the documentation repo.
> feat(Rudderstack): add rudderstack snippet [GRO-692]

- source/subaccounts.rst
Removing beta note and normalizing spelling of 'subaccount' from 'sub-account'
> Traviswalton

- source/_static/rudderstack.js
Upgrade Rudderstack snippet to v3 for security fixes, cookie encryption changes
> feat(Rudderstack): upgrade to Rudderstack v3 lib
