- source/samples/send-simple-message.rst
Change the simple sending instructions to work when users just copy+paste the code into their apps without changing anything.
> Simple sending now sends to user's email

- source/samples/send-mime-message.rst
PHP example is the only one what used `from` parameter. this seems to be unnecessary as it is parsed from message header.
plus none of the other code examples in different languages require `from` parameter
> removed `from` parameter from PHP example

- source/samples/send-complex-message.rst
The at sign will be removed in Guzzle3: https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Http/Message/PostFile.php#L47
Aslo, in Guzzle5 it will only cause trouble. So we should not encourage users to add it...
> You should not have a @ sign before filepath

- source/libraries.rst
The docs indicate that the PHP library can be used on 5.3.x, but the library's `composer.json` file specifies 5.4.0 (probably a result of using Guzzle 5 as a dependency).
> Fix minimum PHP version listed for PHP library

- source/quickstart-sending.rst
Users often have trouble finding their SMTP credentials. Adding this to the quickstart guide will help point them in the right direction.
> Added where to find API key and SMTP creds

- source/samples/get-webhooks.rst
Make webhooks examples consistent by removing /bounces/ part of URL
> Make webhooks examples consistent

- source/user_manual.rst
Occasionally users will submit large X-Mailgun-Variables headers with messages, which will fail during expansion.  Add a suggestion to perform folding to reduce likelihood of this error.
> Added recommendation to fold long X-Mailgun-Variables headers

- source/user_manual.rst
- Sofware to software
- second to seconds (where plural is appropriate)
> Updated two minor typos

- source/best_practices.rst
- source/faqs.rst
- source/libraries.rst
1. Misspelling 
2. Invalid/old link that needed to be updated.
3. Grammar and style changes to FAQs/Best Practices
> fix minor typos in libraries

- source/samples/smtp-send-simple-message.rst
Original referenced smtp.mailgun.com which caused SSL errors as the certificate is signed for *.mailgun.org
> Correct ruby smtp address to smtp.mailgun.org

- source/samples/get-validate.rst
It was everything but obvious by looking at the PHP version of https://documentation.mailgun.com/api-email-validation.html#example what the structure of `$result` is. I had to `var_dump` it first to figure that out.
> Improve PHP sample to show how to check `is_valid`

- source/api-sending.rst
Table formatting was broken, so the actual list of available parameters for sending through the API was not being displayed. Small adjustment so that the table shows.
> Adjust formatting to display Sending Parameters

- source/user_manual.rst
Batch sending requires adding recipient variables in order for messages to be processed correctly.  Some Mailgun users need to submit by SMTP.
The currently documented method for adding recipient variables to a MIME message is to create another mimepart and change the overall Content-Type to "multipart/mailgun-variables".  Many MIME encapsulation libraries don't permit modification of the entire message's Content-Type to a custom value, making it impossible to add recipient variables to MIME messages for batch sending.
This exposes the X-Mailgun-Recipient-Variables feature to permit these client libraries to use recipient variables.  This method is also easier than creating another mimepart and altering the overall content-type.
> Added X-Mailgun-Recipient-Variables header information

- source/api-sending.rst
Message retrieve URLs are supposed to be obtained from events or webhook and used as is. They should not be constructed by our customers.
> Remove retrieve URL prefix

- source/user_manual.rst
Replaced the Note about configuring firewall with SMTP/API IP with a Warning to not use IP ACLs.
"Note If you need to configure your firewall, our SMTP/API IP is: 50.56.21.178. This is subject to change without notice!"
> WIP: Changed Note about API/HTTP IP

- source/_templates/layout.html
Variables at the top of the layout template are not working...?
The site is hard-coded everywhere else in the template, so might as well hard-code it for the panel URL as well :)
> Fix control panel link (#189)

- source/api-routes.rst
I was a little confused if store() actually took URLs in a different syntax and if stop() was a different kind of function due to its different header.
Check the rich diff for a better view.
> Fix routing action documentation typos

- source/user_manual.rst
The documentation currently specifies an attachment size limit of 25MB, but we've confirmed via ticket 304669 that the actual attachment limit is 50MB.
> Update attachment size from 25MB to 50MB

- source/user_manual.rst
Doing a `==` comparison for hex digests could lead to timing attack vulnerabilities. By using Python's `compare_digest`, it would do a constant-time check by using byte operations. A timing attack on that would only reveal the length of the hashes, and not the values.
More here: https://codahale.com/a-lesson-in-timing-attacks/
- Ruby and PHP sample codes have to be updated too. I just don't know if there is a built-in library that does constant-time comparison correctly in those languages.
> Use compare_digest in Python when comparing hex digests

- source/user_manual.rst
There's no documentation on this although there is an example in this post:
http://blog.mailgun.com/closing-the-loop-between-your-customer-data-and-your-email-data/
I've tested it and it seems to work with unique recipient id's showing up in webhooks.
> Added info and example of using templating in custom variables.

- source/user_manual.rst
"it's" expands to "it is" and doesn't make sense here; "its" is possessive.
> Fix it's vs its grammar.

- source/user_manual.rst
Since we are checking that the timestamp is fresh, we should not assume that the server `time()` will be greater than the `$timestamp` in the received webhook and calculate absolute time difference.
Not doing so could cause timestamps with an arbitrary future date to be considered for validation instead than  discarded.
> Absolute time difference in PHP code example

- source/user_manual.rst
The max message size we support is actually 25MB, not 50MB.
> Correct max size

- source/samples/send-complex-message.rst
files tuple should be following
('attachment' ,( filename, content, content_type))
or 
('attachment' ,( filename, content))  #when content_type default is application/octet-stream
> Fix python sample code

- source/_templates/layout.html
The node.js examples aren't currently hidden. Inspector shows the "display: none" is missing from the div class highlight_js. Updating the id from lang_node to lang_js should resolve it.
Just throwing in pics for quick reference:
> Node.js missing "display: none" element

- source/api-campaigns.rst
- source/api-domains.rst
- source/api-email-validation.rst
- source/api-intro.rst
- source/api-ips.rst
- source/api-routes.rst
- source/api-sending.rst
- source/api-tags.rst
- source/best_practices.rst
- source/faqs.rst
- source/lower-bounce-rate.rst
- source/quickstart-events.rst
- source/quickstart-sending.rst
- source/razor.rst
- source/samples/add-domain-ip.rst
- source/samples/get-domain-ips.rst
- source/samples/get-domain-tracking.rst
- source/samples/get-ip.rst
- source/samples/get-ips.rst
- source/user_manual.rst
*Corrected Domains API tracking params
*Removed most references to campaigns
*Updated references to tabs and other non-existent content within control panel
*Cleaned up some formatting inconsistencies
> Domain param errors, remove campaign references, general cleanup

- source/samples/remove-domain-ip.rst
Current:
curl -s --user 'api:YOUR_API_KEY' -X DELETE \
https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/ips/127.0.0.1
Should be:
curl -s --user 'api:YOUR_API_KEY' -X DELETE \
https://api.mailgun.net/v3/domains/YOUR_DOMAIN_NAME/ips/127.0.0.1
If you submit the first one nothing happens because it doesn't call the domains. Added /domains to the URLs
> Update add /domains

- source/api-events.rst
- source/api-suppressions.rst
- source/api-webhooks-deprecated.rst
- source/api-webhooks.rst
- source/api_reference.rst
- source/samples/add-webhook.rst
- source/samples/delete-webhook.rst
- source/samples/get-webhook.rst
- source/samples/update-webhook.rst
- source/user_manual.rst
1. the events examples are refreshed
2. Webhooks(deprecated) is removed from the main left tree menu and available as a link from the top of the webhooks page
3. Webhooks section of the User Manual heavily reworked:
- all the legacy webhooks data formats are moved to the "webhooks(deprecated)" page
- the new webhook payload is described, a reference to the Events Structure section is added
- Tracking bounces and Tracking Failures sections are merged
> Update webhooks documentation, refresh the events examples

- source/api-domains.rst
ips is a new, optional parameter when creating a new domain.
> update parameters for /v2/domains POST

- source/api-domains.rst
Shared IPs can also be requested so corrected the wording. Reworked the mention of error returns.
> correction for dedicated vs shared; reword error condition

- source/samples/resend-simple-message.rst
- source/samples/send-complex-message.rst
- source/samples/send-connection.rst
- source/samples/send-inline-image.rst
- source/samples/send-message-no-tracking.rst
- source/samples/send-mime-message.rst
- source/samples/send-scheduled-message.rst
- source/samples/send-simple-message.rst
- source/samples/send-tagged-message.rst
- source/samples/send-template-message.rst
All Java POST examples to use `field` to build request bodies as
`queryString` is incorrect for POSTs and will usually result in a `414`
response.
> Use `field` instead of `queryString`

- source/api-sending.rst
When using the `message/rfc2822` header, the response contains a `recipients` field and no `recipient`
This fixes the documentation to match but I'd like to note that this is an inconsistency between retrieving the message through the storage endpoint and retrieving the message through the notify webhook.
> fix recipient/recipients in documentation

- source/samples/send-simple-message.rst
Remove extraneous var in node.js simple-send-message example, normalize other parameters.
> Clean up node.js example.

- source/samples/get-mailing-lists.rst
Should be `mailgun.get` as opposed to `mailgun.post`.
> Fix get-mailing-lists call for JS

- source/api-sending.rst
Include recipient-variables option in the list of parameters for sending via the API
> Document recipient-variables parameter

- source/api-domains.rst
"message" is consistently "Domain DNS records have been updated" even when the target domain has not actually been verified.
> Update domains docs

- source/_static/samples.js
- source/api-intro.rst
- source/quickstart.rst
- source/user_manual.rst
1. Comment out hide function for code samples.
2. API Intro page
- add labels to remove build warnings
- fix table spacing to remove build warnings
3. Add label to Quickstart page for linking (and to remove build warnings)
4. Add label to Verifying Your Domain for linking (and to remove build warnings)
> Fix documentation build errors and php block CSS.

- source/api-email-validation.rst
The `parts` parameter previously had the type "string", while it was an object, according to the provided example.
> Fix wrong parameter type in email validation response.

- source/samples/get-parse.rst
- source/samples/get-validate.rst
- source/samples/get-validate4.rst
- use RestClient's GET built-in GET parameter serialisation
- use single line hash declaration
> Improve Ruby Examples for email validation REST API calls

- source/samples/smtp-send-simple-message.rst
rails does not allow to send emails to smtp.mailgun.com, while the same works without any with the domain smtp.mailgun.org. 
The settings tab under the domain also suggests smtp.mailgun.org
> update smtp server to point to .org instead of com

- source/samples/get-validate4.rst
The examples for v4 are showing pubkey and v4 currently doesn't support pubkey.
> v4 validation uses private key not public key

- source/libraries.rst
As per @phongamus' comment on https://github.com/mailgun/mailgun-php/issues/489, I've updated the documentation to be consistent in using the correct instantiation.
> Fix inconsistency in documentation

- source/user_manual.rst
`-H` in the example causes the X-Mailgun-Variables header to not be passed along within the API call and leaves any placeholders such as `{{name}}` as `{{name}}` in the final rendered result when sent to a recipient.
This could be misleading to customers testing sending with Templates
> Update Template bash example

- source/api-events.rst
The section on adding new fields seems to be missing an S when discussing
existing fields in the API; here we add it to try and correct that situation.
> Pluraise word

- source/api-events.rst
Different paid plan subscriptions have varying log retention. The current doc says 30 days for all paid plans. This update is to clarify log retention differs per plan.
> Update to log retention wording

- source/api-stats.rst
We suspect that after the migration to C* 3 scout legacy stats endpoints stopped working and no one noticed. We should remove this route as it's been deprecated for over 2 years.
> PIP-437: Remove legacy stats documentation

- source/api-email-validation.rst
`api_key` is an unsupported param in `v4` email validations and should be removed to prevent any confusion.
> Update doc to remove unsupported param

- source/api-events.rst
The documentation misleadingly implied all events track recipients as a
single "recipient" attribute. Stored events, however, track all of the
recipients in the source email. This has led to confusion and support
tickets from some customers.
> Differentiate between recipient and recipients

- source/api-sending.rst
Under AMP, updated "copmose" to "compose"
> Spelling error

- source/api-email-validation.rst
In some cases the email validation API may return the 'risk' field as 'unknown' this was undocumented. :)
Example response:
```
{
"address": "not-the-real-address@example.org",
"is_disposable_address": false,
"is_role_address": false,
"reason": [
"smtp_connection_error"
],
"result": "unknown",
"risk": "unknown"
}
```
> Add ‘unknown’ to risk description.

- source/samples/add-domain.rst
Currently, `$domain` in the PHP sample for adding a domain is never used. The `name` key had a hard-coded value. Just updated for clarity.
> Add a Domain: PHP sample should use $domain

- source/user_manual.rst
Adds a node.js example to the "Securing Webhooks" section of the user manual
> Add node.js signature verification example to documentation

- source/user_manual.rst
In python3 as oppose to python2, there is no `unicode` function.
Moreover hmac expects bytes as input and not str- otherwise throws exception.
Tested and verified in python 3.7.2.
> Fix python sample of hmac verification to be python3 compatible

- source/user_manual.rst
I'd been successfully sending email some of the time using the existing example, but also seeing some `550 5.7.1 Relaying denied` failures; I think this change does the trick. I found this at https://serverfault.com/a/731598/563221 -- the source cited there ([archived](https://web.archive.org/web/20170627085127/http://kb.philross.co.uk/2008/03/15/configuring-exim-to-use-gmail-as-a-smarthost/)) says
> $host_address is used for hosts_require_auth and hosts_require_tls instead of smtp.gmail.com to avoid occasional 530 5.5.1 Authentication Required errors. These are caused by the changing IP addresses in DNS queries for smtp.gmail.com. $host_address will expand to the particular IP address that was resolved by the gmail_route router.
>
> <; is required for the hosts_require_auth and …
> Allow for IPv6, correct indentation

- source/samples/templates/create-template-usage.rst
The template name does not contain valid characters such as: [a-z0-9.-_~]
> Fix characters not allowed in template name

- source/libraries.rst
The `create` method will return the `Mailgun` object, the `new` keyword causes an error
> Correct PHP Library instructions

- source/user_manual.rst
`theses` -> `these`
`programmaticaly` => `programmatically`
> Fix misspellings

- source/libraries.rst
The base URL for the Mailgun blog changed at some point in the past, and the old URL redirected users to the blog's front page rather than the SDK intro post.
> Update the Official Mailgun Ruby SDK URL

- source/_templates/layout.html
This is a change to the layout.html file for documentation.mailgun.com.  The change adds a  `<script>` tag/statement provided by Forethought.AI so that their AI Help Widget, Agatha, can be installed upon our technical documentation page.
> added forethought widget

- source/quickstart-sending.rst
- source/user_manual.rst
This commit fixes incorrect sender policy framework URLs across the docs.
Old/Incorrect URL: http://www.openspf.org/Introduction
Correct URL: http://www.open-spf.org/Introduction
> Fix incorrect openspf URLs

- source/api-webhooks.rst
Just a simple typo fix – see diff
> Fix typo in documentation

- README.md
This commit adds a light section to the readme with info on deployment, hosting, and debugging failed builds.
> Update readme with information on deployment and hosting

- source/api-mailinglists.rst
This pull request updates the documentation for the `POST /lists/<list>/members.json` API call for mailing lists to let users know if they do not include the `"subscribed"` key with a value in each member in the list they pass the value will default to `true`.
> PIP-891: POST /lists/<list>/members.json Documentation Update

- source/api-email-preview.rst
This commit:
* Removes the mention of `image_blocking` property as it is no longer supported/exposed.
* Removes the mention of the `free` property as it is also deprecated.
> Remove deprecated fields from Email Preview docs

- source/samples/smtp-send-simple-message.rst
Support request to add Node.js example for sending via SMTP. Currently the documentation shows nothing when the user selects Node.js for the code example.
> Add Node.js example for sending via SMTP

- source/faqs.rst
The documentation link under "Do I control the unsubscribe handling or do you?" is outdated. Updated the link
> Update unsubscribe documentation link

- source/_templates/layout.html
Changing data-ft-language=""
to data-ft-language="en"
Since the MG widget is now language-aware, it must have one of the corresponding language values:  "es" or "en".
> patch forethought in layout.html

- source/user_manual.rst
Adding documentation for new `disable-tracking` html tag attribute for disabling click tracking for specific links in hte html body. 
https://mailgun.atlassian.net/browse/PIP-1978
> PIP-1978: add documentation for disable-tracking html tag attribute

- source/api-blocklist-monitoring.rst
This PR documents the two following endpoints:
* `GET /v1/blocklist-monitoring/events`
* `GET /v1/blocklist-monitoring/blocklists`
> Add documentation for blocklist monitoring events API

- source/api-intro.rst
wikipedia link json objects is deprecated or not working.
> fixing broken wiki link

- source/api-deliverability-alerts.rst
- source/api-inbox-placement.rst
- source/samples/create-inbox-placement-test.rst
This PR:
- documents `POST /v4/inbox/tests`.
- documents `GET /v4/inbox/providers`.
- adds `domain_listed/delisted` events to the alerts docs.
> Add documentation for IBP test create endpoint

- source/api-stats.rst
Total field is missing from the docs although it's present in the Stats response.
Should some sort of comment be added or is it self-explanatory?
Found by https://github.com/mailgun/mailgun-go/pull/298
> Add Total field to the temporary failed stats

- source/api-suppressions.rst
Fix a missing comma in the example response for "View a single whitelist record"
> Fix API example response for "View a single whitelist record"

- source/api-ip-pools.rst
Fix an error in second example response shown in the [IP Pools API docs](https://documentation.mailgun.com/en/latest/api-ip-pools.html#examples).
Additionally, use quoting of the object keys so they are consistent with the rest of the API docs (even though the blocks are labelled as `javascript`, almost all of them are valid JSON, and formatted this way).
> Fix IP pools sample response
